package com.lds.vo;
// Generated 13 juil. 2012 07:24:47 by Hibernate Tools 3.2.1.GA



/**
 * AffaireId generated by hbm2java
 */
public class AffaireId  implements java.io.Serializable {


     private String idprojet;
     private String numaffaire;

    public AffaireId() {
    }

    public AffaireId(String idprojet, String numaffaire) {
       this.idprojet = idprojet;
       this.numaffaire = numaffaire;
    }
   
    public String getIdprojet() {
        return this.idprojet;
    }
    
    public void setIdprojet(String idprojet) {
        this.idprojet = idprojet;
    }
    public String getNumaffaire() {
        return this.numaffaire;
    }
    
    public void setNumaffaire(String numaffaire) {
        this.numaffaire = numaffaire;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AffaireId) ) return false;
		 AffaireId castOther = ( AffaireId ) other; 
         
		 return ( (this.getIdprojet()==castOther.getIdprojet()) || ( this.getIdprojet()!=null && castOther.getIdprojet()!=null && this.getIdprojet().equals(castOther.getIdprojet()) ) )
 && ( (this.getNumaffaire()==castOther.getNumaffaire()) || ( this.getNumaffaire()!=null && castOther.getNumaffaire()!=null && this.getNumaffaire().equals(castOther.getNumaffaire()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdprojet() == null ? 0 : this.getIdprojet().hashCode() );
         result = 37 * result + ( getNumaffaire() == null ? 0 : this.getNumaffaire().hashCode() );
         return result;
   }   


}


