package com.lds.vo;
// Generated 20 juil. 2012 11:53:18 by Hibernate Tools 3.2.1.GA



/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private ArticleId id;
     private Element element;
     private String descarticle;
     private Integer qntarticle;
     private String marque;

    public Article() {
    }

	
    public Article(ArticleId id, Element element) {
        this.id = id;
        this.element = element;
    }
    public Article(ArticleId id, Element element, String descarticle, Integer qntarticle, String marque) {
       this.id = id;
       this.element = element;
       this.descarticle = descarticle;
       this.qntarticle = qntarticle;
       this.marque = marque;
    }
   
    public ArticleId getId() {
        return this.id;
    }
    
    public void setId(ArticleId id) {
        this.id = id;
    }
    public Element getElement() {
        return this.element;
    }
    
    public void setElement(Element element) {
        this.element = element;
    }
    public String getDescarticle() {
        return this.descarticle;
    }
    
    public void setDescarticle(String descarticle) {
        this.descarticle = descarticle;
    }
    public Integer getQntarticle() {
        return this.qntarticle;
    }
    
    public void setQntarticle(Integer qntarticle) {
        this.qntarticle = qntarticle;
    }
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }




}


