package com.lds.vo;
// Generated 25 aout 2012 10:08:18 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private String idarticle;
     private String descarticle;
     private Integer qntarticle;
     private String marque;
     private Set detailssortiearticles = new HashSet(0);
     private Set detailsbcarticles = new HashSet(0);
     private Set detailsbrarticles = new HashSet(0);
     private Set detailsdemandearticles = new HashSet(0);

    public Article() {
    }

	
    public Article(String idarticle) {
        this.idarticle = idarticle;
    }
    public Article(String idarticle, String descarticle, Integer qntarticle, String marque, Set detailssortiearticles, Set detailsbcarticles, Set detailsbrarticles, Set detailsdemandearticles) {
       this.idarticle = idarticle;
       this.descarticle = descarticle;
       this.qntarticle = qntarticle;
       this.marque = marque;
       this.detailssortiearticles = detailssortiearticles;
       this.detailsbcarticles = detailsbcarticles;
       this.detailsbrarticles = detailsbrarticles;
       this.detailsdemandearticles = detailsdemandearticles;
    }
   
    public String getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(String idarticle) {
        this.idarticle = idarticle;
    }
    public String getDescarticle() {
        return this.descarticle;
    }
    
    public void setDescarticle(String descarticle) {
        this.descarticle = descarticle;
    }
    public Integer getQntarticle() {
        return this.qntarticle;
    }
    
    public void setQntarticle(Integer qntarticle) {
        this.qntarticle = qntarticle;
    }
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }
    public Set getDetailssortiearticles() {
        return this.detailssortiearticles;
    }
    
    public void setDetailssortiearticles(Set detailssortiearticles) {
        this.detailssortiearticles = detailssortiearticles;
    }
    public Set getDetailsbcarticles() {
        return this.detailsbcarticles;
    }
    
    public void setDetailsbcarticles(Set detailsbcarticles) {
        this.detailsbcarticles = detailsbcarticles;
    }
    public Set getDetailsbrarticles() {
        return this.detailsbrarticles;
    }
    
    public void setDetailsbrarticles(Set detailsbrarticles) {
        this.detailsbrarticles = detailsbrarticles;
    }
    public Set getDetailsdemandearticles() {
        return this.detailsdemandearticles;
    }
    
    public void setDetailsdemandearticles(Set detailsdemandearticles) {
        this.detailsdemandearticles = detailsdemandearticles;
    }




}


