package com.lds.vo;
// Generated 11 juil. 2012 11:29:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bonreception generated by hbm2java
 */
public class Bonreception  implements java.io.Serializable {


     private String numreception;
     private Boncommande boncommande;
     private Date datereception;
     private Set detailsbrelements = new HashSet(0);

    public Bonreception() {
    }

	
    public Bonreception(String numreception, Boncommande boncommande) {
        this.numreception = numreception;
        this.boncommande = boncommande;
    }
    public Bonreception(String numreception, Boncommande boncommande, Date datereception, Set detailsbrelements) {
       this.numreception = numreception;
       this.boncommande = boncommande;
       this.datereception = datereception;
       this.detailsbrelements = detailsbrelements;
    }
   
    public String getNumreception() {
        return this.numreception;
    }
    
    public void setNumreception(String numreception) {
        this.numreception = numreception;
    }
    public Boncommande getBoncommande() {
        return this.boncommande;
    }
    
    public void setBoncommande(Boncommande boncommande) {
        this.boncommande = boncommande;
    }
    public Date getDatereception() {
        return this.datereception;
    }
    
    public void setDatereception(Date datereception) {
        this.datereception = datereception;
    }
    public Set getDetailsbrelements() {
        return this.detailsbrelements;
    }
    
    public void setDetailsbrelements(Set detailsbrelements) {
        this.detailsbrelements = detailsbrelements;
    }




}


