package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bonreception generated by hbm2java
 */
public class Bonreception  implements java.io.Serializable {


     private String numreception;
     private Fourniture fourniture;
     private Boncommande boncommande;
     private Date datereception;
     private Integer qntlivre;
     private Set detailsbrarticles = new HashSet(0);

    public Bonreception() {
    }

	
    public Bonreception(String numreception, Boncommande boncommande) {
        this.numreception = numreception;
        this.boncommande = boncommande;
    }
    public Bonreception(String numreception, Fourniture fourniture, Boncommande boncommande, Date datereception, Integer qntlivre, Set detailsbrarticles) {
       this.numreception = numreception;
       this.fourniture = fourniture;
       this.boncommande = boncommande;
       this.datereception = datereception;
       this.qntlivre = qntlivre;
       this.detailsbrarticles = detailsbrarticles;
    }
   
    public String getNumreception() {
        return this.numreception;
    }
    
    public void setNumreception(String numreception) {
        this.numreception = numreception;
    }
    public Fourniture getFourniture() {
        return this.fourniture;
    }
    
    public void setFourniture(Fourniture fourniture) {
        this.fourniture = fourniture;
    }
    public Boncommande getBoncommande() {
        return this.boncommande;
    }
    
    public void setBoncommande(Boncommande boncommande) {
        this.boncommande = boncommande;
    }
    public Date getDatereception() {
        return this.datereception;
    }
    
    public void setDatereception(Date datereception) {
        this.datereception = datereception;
    }
    public Integer getQntlivre() {
        return this.qntlivre;
    }
    
    public void setQntlivre(Integer qntlivre) {
        this.qntlivre = qntlivre;
    }
    public Set getDetailsbrarticles() {
        return this.detailsbrarticles;
    }
    
    public void setDetailsbrarticles(Set detailsbrarticles) {
        this.detailsbrarticles = detailsbrarticles;
    }




}


