package com.lds.vo;
// Generated 25 aout 2012 10:08:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bonsortie generated by hbm2java
 */
public class Bonsortie  implements java.io.Serializable {


     private String idsortie;
     private Projet projet;
     private Personnel personnel;
     private Date datesortie;
     private String descsortie;
     private Set detailssortiefournitures = new HashSet(0);
     private Set detailssortiearticles = new HashSet(0);

    public Bonsortie() {
    }

	
    public Bonsortie(String idsortie, Projet projet, Personnel personnel) {
        this.idsortie = idsortie;
        this.projet = projet;
        this.personnel = personnel;
    }
    public Bonsortie(String idsortie, Projet projet, Personnel personnel, Date datesortie, String descsortie, Set detailssortiefournitures, Set detailssortiearticles) {
       this.idsortie = idsortie;
       this.projet = projet;
       this.personnel = personnel;
       this.datesortie = datesortie;
       this.descsortie = descsortie;
       this.detailssortiefournitures = detailssortiefournitures;
       this.detailssortiearticles = detailssortiearticles;
    }
   
    public String getIdsortie() {
        return this.idsortie;
    }
    
    public void setIdsortie(String idsortie) {
        this.idsortie = idsortie;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public Personnel getPersonnel() {
        return this.personnel;
    }
    
    public void setPersonnel(Personnel personnel) {
        this.personnel = personnel;
    }
    public Date getDatesortie() {
        return this.datesortie;
    }
    
    public void setDatesortie(Date datesortie) {
        this.datesortie = datesortie;
    }
    public String getDescsortie() {
        return this.descsortie;
    }
    
    public void setDescsortie(String descsortie) {
        this.descsortie = descsortie;
    }
    public Set getDetailssortiefournitures() {
        return this.detailssortiefournitures;
    }
    
    public void setDetailssortiefournitures(Set detailssortiefournitures) {
        this.detailssortiefournitures = detailssortiefournitures;
    }
    public Set getDetailssortiearticles() {
        return this.detailssortiearticles;
    }
    
    public void setDetailssortiearticles(Set detailssortiearticles) {
        this.detailssortiearticles = detailssortiearticles;
    }




}


