package com.lds.vo;
// Generated 16 juil. 2012 17:30:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Demandeprix generated by hbm2java
 */
public class Demandeprix  implements java.io.Serializable {


     private String numdemandeprix;
     private Fournisseur fournisseur;
     private String referencedemandeprix;
     private String datedemandeprix;
     private Set detailsdemandeelements = new HashSet(0);

    public Demandeprix() {
    }

	
    public Demandeprix(String numdemandeprix, Fournisseur fournisseur) {
        this.numdemandeprix = numdemandeprix;
        this.fournisseur = fournisseur;
    }
    public Demandeprix(String numdemandeprix, Fournisseur fournisseur, String referencedemandeprix, String datedemandeprix, Set detailsdemandeelements) {
       this.numdemandeprix = numdemandeprix;
       this.fournisseur = fournisseur;
       this.referencedemandeprix = referencedemandeprix;
       this.datedemandeprix = datedemandeprix;
       this.detailsdemandeelements = detailsdemandeelements;
    }
   
    public String getNumdemandeprix() {
        return this.numdemandeprix;
    }
    
    public void setNumdemandeprix(String numdemandeprix) {
        this.numdemandeprix = numdemandeprix;
    }
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }
    public String getReferencedemandeprix() {
        return this.referencedemandeprix;
    }
    
    public void setReferencedemandeprix(String referencedemandeprix) {
        this.referencedemandeprix = referencedemandeprix;
    }
    public String getDatedemandeprix() {
        return this.datedemandeprix;
    }
    
    public void setDatedemandeprix(String datedemandeprix) {
        this.datedemandeprix = datedemandeprix;
    }
    public Set getDetailsdemandeelements() {
        return this.detailsdemandeelements;
    }
    
    public void setDetailsdemandeelements(Set detailsdemandeelements) {
        this.detailsdemandeelements = detailsdemandeelements;
    }




}


