package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA

/**
 * Detailsdemandearticle generated by hbm2java
 */
public class Detailsdemandearticle  implements java.io.Serializable {


     private DetailsdemandearticleId id;
     private Demandeprix demandeprix;
     private Article article;
     private Integer qntdemande;

    public Detailsdemandearticle() {
    }

	
    public Detailsdemandearticle(DetailsdemandearticleId id, Demandeprix demandeprix, Article article) {
        this.id = id;
        this.demandeprix = demandeprix;
        this.article = article;
    }
    public Detailsdemandearticle(DetailsdemandearticleId id, Demandeprix demandeprix, Article article, Integer qntdemande) {
       this.id = id;
       this.demandeprix = demandeprix;
       this.article = article;
       this.qntdemande = qntdemande;
    }
   
    public DetailsdemandearticleId getId() {
        return this.id;
    }
    
    public void setId(DetailsdemandearticleId id) {
        this.id = id;
    }
    public Demandeprix getDemandeprix() {
        return this.demandeprix;
    }
    
    public void setDemandeprix(Demandeprix demandeprix) {
        this.demandeprix = demandeprix;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Integer getQntdemande() {
        return this.qntdemande;
    }
    
    public void setQntdemande(Integer qntdemande) {
        this.qntdemande = qntdemande;
    }




}


