package com.lds.vo;
// Generated 25 aout 2012 10:08:18 by Hibernate Tools 3.2.1.GA



/**
 * Detailsbrfourniture generated by hbm2java
 */
public class Detailsbrfourniture  implements java.io.Serializable {


     private String iddetails;
     private Fourniture fourniture;
     private Bonreception bonreception;
     private Integer qntlivre;

    public Detailsbrfourniture() {
    }

	
    public Detailsbrfourniture(String iddetails, Fourniture fourniture, Bonreception bonreception) {
        this.iddetails = iddetails;
        this.fourniture = fourniture;
        this.bonreception = bonreception;
    }
    public Detailsbrfourniture(String iddetails, Fourniture fourniture, Bonreception bonreception, Integer qntlivre) {
       this.iddetails = iddetails;
       this.fourniture = fourniture;
       this.bonreception = bonreception;
       this.qntlivre = qntlivre;
    }
   
    public String getIddetails() {
        return this.iddetails;
    }
    
    public void setIddetails(String iddetails) {
        this.iddetails = iddetails;
    }
    public Fourniture getFourniture() {
        return this.fourniture;
    }
    
    public void setFourniture(Fourniture fourniture) {
        this.fourniture = fourniture;
    }
    public Bonreception getBonreception() {
        return this.bonreception;
    }
    
    public void setBonreception(Bonreception bonreception) {
        this.bonreception = bonreception;
    }
    public Integer getQntlivre() {
        return this.qntlivre;
    }
    
    public void setQntlivre(Integer qntlivre) {
        this.qntlivre = qntlivre;
    }




}


