package com.lds.vo;
// Generated 25 aout 2012 10:08:18 by Hibernate Tools 3.2.1.GA



/**
 * DetailsfourniturebcId generated by hbm2java
 */
public class DetailsfourniturebcId  implements java.io.Serializable {


     private String numbc;
     private String numfourniture;

    public DetailsfourniturebcId() {
    }

    public DetailsfourniturebcId(String numbc, String numfourniture) {
       this.numbc = numbc;
       this.numfourniture = numfourniture;
    }
   
    public String getNumbc() {
        return this.numbc;
    }
    
    public void setNumbc(String numbc) {
        this.numbc = numbc;
    }
    public String getNumfourniture() {
        return this.numfourniture;
    }
    
    public void setNumfourniture(String numfourniture) {
        this.numfourniture = numfourniture;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsfourniturebcId) ) return false;
		 DetailsfourniturebcId castOther = ( DetailsfourniturebcId ) other; 
         
		 return ( (this.getNumbc()==castOther.getNumbc()) || ( this.getNumbc()!=null && castOther.getNumbc()!=null && this.getNumbc().equals(castOther.getNumbc()) ) )
 && ( (this.getNumfourniture()==castOther.getNumfourniture()) || ( this.getNumfourniture()!=null && castOther.getNumfourniture()!=null && this.getNumfourniture().equals(castOther.getNumfourniture()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumbc() == null ? 0 : this.getNumbc().hashCode() );
         result = 37 * result + ( getNumfourniture() == null ? 0 : this.getNumfourniture().hashCode() );
         return result;
   }   


}


