package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA



/**
 * DetailssortiearticleId generated by hbm2java
 */
public class DetailssortiearticleId  implements java.io.Serializable {


     private String idsortie;
     private String idarticle;

    public DetailssortiearticleId() {
    }

    public DetailssortiearticleId(String idsortie, String idarticle) {
       this.idsortie = idsortie;
       this.idarticle = idarticle;
    }
   
    public String getIdsortie() {
        return this.idsortie;
    }
    
    public void setIdsortie(String idsortie) {
        this.idsortie = idsortie;
    }
    public String getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(String idarticle) {
        this.idarticle = idarticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailssortiearticleId) ) return false;
		 DetailssortiearticleId castOther = ( DetailssortiearticleId ) other; 
         
		 return ( (this.getIdsortie()==castOther.getIdsortie()) || ( this.getIdsortie()!=null && castOther.getIdsortie()!=null && this.getIdsortie().equals(castOther.getIdsortie()) ) )
 && ( (this.getIdarticle()==castOther.getIdarticle()) || ( this.getIdarticle()!=null && castOther.getIdarticle()!=null && this.getIdarticle().equals(castOther.getIdarticle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdsortie() == null ? 0 : this.getIdsortie().hashCode() );
         result = 37 * result + ( getIdarticle() == null ? 0 : this.getIdarticle().hashCode() );
         return result;
   }   


}


