package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA



/**
 * DetailsarticlebesoinId generated by hbm2java
 */
public class DetailsarticlebesoinId  implements java.io.Serializable {


     private String idbesoin;
     private String idarticle;

    public DetailsarticlebesoinId() {
    }

    public DetailsarticlebesoinId(String idbesoin, String idarticle) {
       this.idbesoin = idbesoin;
       this.idarticle = idarticle;
    }
   
    public String getIdbesoin() {
        return this.idbesoin;
    }
    
    public void setIdbesoin(String idbesoin) {
        this.idbesoin = idbesoin;
    }
    public String getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(String idarticle) {
        this.idarticle = idarticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsarticlebesoinId) ) return false;
		 DetailsarticlebesoinId castOther = ( DetailsarticlebesoinId ) other; 
         
		 return ( (this.getIdbesoin()==castOther.getIdbesoin()) || ( this.getIdbesoin()!=null && castOther.getIdbesoin()!=null && this.getIdbesoin().equals(castOther.getIdbesoin()) ) )
 && ( (this.getIdarticle()==castOther.getIdarticle()) || ( this.getIdarticle()!=null && castOther.getIdarticle()!=null && this.getIdarticle().equals(castOther.getIdarticle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdbesoin() == null ? 0 : this.getIdbesoin().hashCode() );
         result = 37 * result + ( getIdarticle() == null ? 0 : this.getIdarticle().hashCode() );
         return result;
   }   


}


