package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA



/**
 * Detailssortiefourniture generated by hbm2java
 */
public class Detailssortiefourniture  implements java.io.Serializable {


     private DetailssortiefournitureId id;
     private Fourniture fourniture;
     private Bonsortie bonsortie;
     private Integer qntsortie;
     private Integer qntretour;

    public Detailssortiefourniture() {
    }

	
    public Detailssortiefourniture(DetailssortiefournitureId id, Fourniture fourniture, Bonsortie bonsortie) {
        this.id = id;
        this.fourniture = fourniture;
        this.bonsortie = bonsortie;
    }
    public Detailssortiefourniture(DetailssortiefournitureId id, Fourniture fourniture, Bonsortie bonsortie, Integer qntsortie, Integer qntretour) {
       this.id = id;
       this.fourniture = fourniture;
       this.bonsortie = bonsortie;
       this.qntsortie = qntsortie;
       this.qntretour = qntretour;
    }
   
    public DetailssortiefournitureId getId() {
        return this.id;
    }
    
    public void setId(DetailssortiefournitureId id) {
        this.id = id;
    }
    public Fourniture getFourniture() {
        return this.fourniture;
    }
    
    public void setFourniture(Fourniture fourniture) {
        this.fourniture = fourniture;
    }
    public Bonsortie getBonsortie() {
        return this.bonsortie;
    }
    
    public void setBonsortie(Bonsortie bonsortie) {
        this.bonsortie = bonsortie;
    }
    public Integer getQntsortie() {
        return this.qntsortie;
    }
    
    public void setQntsortie(Integer qntsortie) {
        this.qntsortie = qntsortie;
    }
    public Integer getQntretour() {
        return this.qntretour;
    }
    
    public void setQntretour(Integer qntretour) {
        this.qntretour = qntretour;
    }




}


