package com.lds.vo;
// Generated 20 juil. 2012 18:55:33 by Hibernate Tools 3.2.1.GA



/**
 * DetailselementbesoinId generated by hbm2java
 */
public class DetailselementbesoinId  implements java.io.Serializable {


     private String idbesoin;
     private String idelement;

    public DetailselementbesoinId() {
    }

    public DetailselementbesoinId(String idbesoin, String idelement) {
       this.idbesoin = idbesoin;
       this.idelement = idelement;
    }
   
    public String getIdbesoin() {
        return this.idbesoin;
    }
    
    public void setIdbesoin(String idbesoin) {
        this.idbesoin = idbesoin;
    }
    public String getIdelement() {
        return this.idelement;
    }
    
    public void setIdelement(String idelement) {
        this.idelement = idelement;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailselementbesoinId) ) return false;
		 DetailselementbesoinId castOther = ( DetailselementbesoinId ) other; 
         
		 return ( (this.getIdbesoin()==castOther.getIdbesoin()) || ( this.getIdbesoin()!=null && castOther.getIdbesoin()!=null && this.getIdbesoin().equals(castOther.getIdbesoin()) ) )
 && ( (this.getIdelement()==castOther.getIdelement()) || ( this.getIdelement()!=null && castOther.getIdelement()!=null && this.getIdelement().equals(castOther.getIdelement()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdbesoin() == null ? 0 : this.getIdbesoin().hashCode() );
         result = 37 * result + ( getIdelement() == null ? 0 : this.getIdelement().hashCode() );
         return result;
   }   


}


