package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA



/**
 * DetailsfourniturebesoinId generated by hbm2java
 */
public class DetailsfourniturebesoinId  implements java.io.Serializable {


     private String idbesoin;
     private String numfourniture;

    public DetailsfourniturebesoinId() {
    }

    public DetailsfourniturebesoinId(String idbesoin, String numfourniture) {
       this.idbesoin = idbesoin;
       this.numfourniture = numfourniture;
    }
   
    public String getIdbesoin() {
        return this.idbesoin;
    }
    
    public void setIdbesoin(String idbesoin) {
        this.idbesoin = idbesoin;
    }
    public String getNumfourniture() {
        return this.numfourniture;
    }
    
    public void setNumfourniture(String numfourniture) {
        this.numfourniture = numfourniture;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsfourniturebesoinId) ) return false;
		 DetailsfourniturebesoinId castOther = ( DetailsfourniturebesoinId ) other; 
         
		 return ( (this.getIdbesoin()==castOther.getIdbesoin()) || ( this.getIdbesoin()!=null && castOther.getIdbesoin()!=null && this.getIdbesoin().equals(castOther.getIdbesoin()) ) )
 && ( (this.getNumfourniture()==castOther.getNumfourniture()) || ( this.getNumfourniture()!=null && castOther.getNumfourniture()!=null && this.getNumfourniture().equals(castOther.getNumfourniture()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdbesoin() == null ? 0 : this.getIdbesoin().hashCode() );
         result = 37 * result + ( getNumfourniture() == null ? 0 : this.getNumfourniture().hashCode() );
         return result;
   }   


}


