package com.lds.vo;
// Generated 25 aout 2012 10:08:18 by Hibernate Tools 3.2.1.GA



/**
 * Detailsarticlebesoin generated by hbm2java
 */
public class Detailsarticlebesoin  implements java.io.Serializable {


     private DetailsarticlebesoinId id;
     private Integer qntbesoin;

    public Detailsarticlebesoin() {
    }

	
    public Detailsarticlebesoin(DetailsarticlebesoinId id) {
        this.id = id;
    }
    public Detailsarticlebesoin(DetailsarticlebesoinId id, Integer qntbesoin) {
       this.id = id;
       this.qntbesoin = qntbesoin;
    }
   
    public DetailsarticlebesoinId getId() {
        return this.id;
    }
    
    public void setId(DetailsarticlebesoinId id) {
        this.id = id;
    }
    public Integer getQntbesoin() {
        return this.qntbesoin;
    }
    
    public void setQntbesoin(Integer qntbesoin) {
        this.qntbesoin = qntbesoin;
    }




}


