package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA



/**
 * DetailsbrarticleId generated by hbm2java
 */
public class DetailsbrarticleId  implements java.io.Serializable {


     private String numreception;
     private String idarticle;

    public DetailsbrarticleId() {
    }

    public DetailsbrarticleId(String numreception, String idarticle) {
       this.numreception = numreception;
       this.idarticle = idarticle;
    }
   
    public String getNumreception() {
        return this.numreception;
    }
    
    public void setNumreception(String numreception) {
        this.numreception = numreception;
    }
    public String getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(String idarticle) {
        this.idarticle = idarticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsbrarticleId) ) return false;
		 DetailsbrarticleId castOther = ( DetailsbrarticleId ) other; 
         
		 return ( (this.getNumreception()==castOther.getNumreception()) || ( this.getNumreception()!=null && castOther.getNumreception()!=null && this.getNumreception().equals(castOther.getNumreception()) ) )
 && ( (this.getIdarticle()==castOther.getIdarticle()) || ( this.getIdarticle()!=null && castOther.getIdarticle()!=null && this.getIdarticle().equals(castOther.getIdarticle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumreception() == null ? 0 : this.getNumreception().hashCode() );
         result = 37 * result + ( getIdarticle() == null ? 0 : this.getIdarticle().hashCode() );
         return result;
   }   


}


