package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA



/**
 * DetailsbcarticleId generated by hbm2java
 */
public class DetailsbcarticleId  implements java.io.Serializable {


     private String numbc;
     private String idarticle;

    public DetailsbcarticleId() {
    }

    public DetailsbcarticleId(String numbc, String idarticle) {
       this.numbc = numbc;
       this.idarticle = idarticle;
    }
   
    public String getNumbc() {
        return this.numbc;
    }
    
    public void setNumbc(String numbc) {
        this.numbc = numbc;
    }
    public String getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(String idarticle) {
        this.idarticle = idarticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsbcarticleId) ) return false;
		 DetailsbcarticleId castOther = ( DetailsbcarticleId ) other; 
         
		 return ( (this.getNumbc()==castOther.getNumbc()) || ( this.getNumbc()!=null && castOther.getNumbc()!=null && this.getNumbc().equals(castOther.getNumbc()) ) )
 && ( (this.getIdarticle()==castOther.getIdarticle()) || ( this.getIdarticle()!=null && castOther.getIdarticle()!=null && this.getIdarticle().equals(castOther.getIdarticle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumbc() == null ? 0 : this.getNumbc().hashCode() );
         result = 37 * result + ( getIdarticle() == null ? 0 : this.getIdarticle().hashCode() );
         return result;
   }   


}


