package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Detailsbcarticle generated by hbm2java
 */
public class Detailsbcarticle  implements java.io.Serializable {


     private DetailsbcarticleId id;
     private Boncommande boncommande;
     private Article article;
     private String qntcommande;
     private BigDecimal prixunitaire;

    public Detailsbcarticle() {
    }

	
    public Detailsbcarticle(DetailsbcarticleId id, Boncommande boncommande, Article article) {
        this.id = id;
        this.boncommande = boncommande;
        this.article = article;
    }
    public Detailsbcarticle(DetailsbcarticleId id, Boncommande boncommande, Article article, String qntcommande, BigDecimal prixunitaire) {
       this.id = id;
       this.boncommande = boncommande;
       this.article = article;
       this.qntcommande = qntcommande;
       this.prixunitaire = prixunitaire;
    }
   
    public DetailsbcarticleId getId() {
        return this.id;
    }
    
    public void setId(DetailsbcarticleId id) {
        this.id = id;
    }
    public Boncommande getBoncommande() {
        return this.boncommande;
    }
    
    public void setBoncommande(Boncommande boncommande) {
        this.boncommande = boncommande;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public String getQntcommande() {
        return this.qntcommande;
    }
    
    public void setQntcommande(String qntcommande) {
        this.qntcommande = qntcommande;
    }
    public BigDecimal getPrixunitaire() {
        return this.prixunitaire;
    }
    
    public void setPrixunitaire(BigDecimal prixunitaire) {
        this.prixunitaire = prixunitaire;
    }




}


