package com.lds.vo;
// Generated 25 aout 2012 10:08:18 by Hibernate Tools 3.2.1.GA



/**
 * DetailssortiefournitureId generated by hbm2java
 */
public class DetailssortiefournitureId  implements java.io.Serializable {


     private String idsortie;
     private String numfourniture;

    public DetailssortiefournitureId() {
    }

    public DetailssortiefournitureId(String idsortie, String numfourniture) {
       this.idsortie = idsortie;
       this.numfourniture = numfourniture;
    }
   
    public String getIdsortie() {
        return this.idsortie;
    }
    
    public void setIdsortie(String idsortie) {
        this.idsortie = idsortie;
    }
    public String getNumfourniture() {
        return this.numfourniture;
    }
    
    public void setNumfourniture(String numfourniture) {
        this.numfourniture = numfourniture;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailssortiefournitureId) ) return false;
		 DetailssortiefournitureId castOther = ( DetailssortiefournitureId ) other; 
         
		 return ( (this.getIdsortie()==castOther.getIdsortie()) || ( this.getIdsortie()!=null && castOther.getIdsortie()!=null && this.getIdsortie().equals(castOther.getIdsortie()) ) )
 && ( (this.getNumfourniture()==castOther.getNumfourniture()) || ( this.getNumfourniture()!=null && castOther.getNumfourniture()!=null && this.getNumfourniture().equals(castOther.getNumfourniture()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdsortie() == null ? 0 : this.getIdsortie().hashCode() );
         result = 37 * result + ( getNumfourniture() == null ? 0 : this.getNumfourniture().hashCode() );
         return result;
   }   


}


