package com.lds.vo;
// Generated 20 juil. 2012 18:55:33 by Hibernate Tools 3.2.1.GA



/**
 * DetailsprivuserId generated by hbm2java
 */
public class DetailsprivuserId  implements java.io.Serializable {


     private String idpersonnel;
     private String idpriv;

    public DetailsprivuserId() {
    }

    public DetailsprivuserId(String idpersonnel, String idpriv) {
       this.idpersonnel = idpersonnel;
       this.idpriv = idpriv;
    }
   
    public String getIdpersonnel() {
        return this.idpersonnel;
    }
    
    public void setIdpersonnel(String idpersonnel) {
        this.idpersonnel = idpersonnel;
    }
    public String getIdpriv() {
        return this.idpriv;
    }
    
    public void setIdpriv(String idpriv) {
        this.idpriv = idpriv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsprivuserId) ) return false;
		 DetailsprivuserId castOther = ( DetailsprivuserId ) other; 
         
		 return ( (this.getIdpersonnel()==castOther.getIdpersonnel()) || ( this.getIdpersonnel()!=null && castOther.getIdpersonnel()!=null && this.getIdpersonnel().equals(castOther.getIdpersonnel()) ) )
 && ( (this.getIdpriv()==castOther.getIdpriv()) || ( this.getIdpriv()!=null && castOther.getIdpriv()!=null && this.getIdpriv().equals(castOther.getIdpriv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonnel() == null ? 0 : this.getIdpersonnel().hashCode() );
         result = 37 * result + ( getIdpriv() == null ? 0 : this.getIdpriv().hashCode() );
         return result;
   }   


}


