package com.lds.vo;
// Generated 20 juil. 2012 11:53:18 by Hibernate Tools 3.2.1.GA



/**
 * DetailsdemandeelementId generated by hbm2java
 */
public class DetailsdemandeelementId  implements java.io.Serializable {


     private String numdemandeprix;
     private String idelement;

    public DetailsdemandeelementId() {
    }

    public DetailsdemandeelementId(String numdemandeprix, String idelement) {
       this.numdemandeprix = numdemandeprix;
       this.idelement = idelement;
    }
   
    public String getNumdemandeprix() {
        return this.numdemandeprix;
    }
    
    public void setNumdemandeprix(String numdemandeprix) {
        this.numdemandeprix = numdemandeprix;
    }
    public String getIdelement() {
        return this.idelement;
    }
    
    public void setIdelement(String idelement) {
        this.idelement = idelement;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailsdemandeelementId) ) return false;
		 DetailsdemandeelementId castOther = ( DetailsdemandeelementId ) other; 
         
		 return ( (this.getNumdemandeprix()==castOther.getNumdemandeprix()) || ( this.getNumdemandeprix()!=null && castOther.getNumdemandeprix()!=null && this.getNumdemandeprix().equals(castOther.getNumdemandeprix()) ) )
 && ( (this.getIdelement()==castOther.getIdelement()) || ( this.getIdelement()!=null && castOther.getIdelement()!=null && this.getIdelement().equals(castOther.getIdelement()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumdemandeprix() == null ? 0 : this.getNumdemandeprix().hashCode() );
         result = 37 * result + ( getIdelement() == null ? 0 : this.getIdelement().hashCode() );
         return result;
   }   


}


