package com.lds.vo;
// Generated 16 juil. 2012 17:30:31 by Hibernate Tools 3.2.1.GA



/**
 * Detailsdemandeelement generated by hbm2java
 */
public class Detailsdemandeelement  implements java.io.Serializable {


     private DetailsdemandeelementId id;
     private Element element;
     private Demandeprix demandeprix;
     private Integer qntdemande;

    public Detailsdemandeelement() {
    }

	
    public Detailsdemandeelement(DetailsdemandeelementId id, Element element, Demandeprix demandeprix) {
        this.id = id;
        this.element = element;
        this.demandeprix = demandeprix;
    }
    public Detailsdemandeelement(DetailsdemandeelementId id, Element element, Demandeprix demandeprix, Integer qntdemande) {
       this.id = id;
       this.element = element;
       this.demandeprix = demandeprix;
       this.qntdemande = qntdemande;
    }
   
    public DetailsdemandeelementId getId() {
        return this.id;
    }
    
    public void setId(DetailsdemandeelementId id) {
        this.id = id;
    }
    public Element getElement() {
        return this.element;
    }
    
    public void setElement(Element element) {
        this.element = element;
    }
    public Demandeprix getDemandeprix() {
        return this.demandeprix;
    }
    
    public void setDemandeprix(Demandeprix demandeprix) {
        this.demandeprix = demandeprix;
    }
    public Integer getQntdemande() {
        return this.qntdemande;
    }
    
    public void setQntdemande(Integer qntdemande) {
        this.qntdemande = qntdemande;
    }




}


