package com.lds.vo;
// Generated 20 juil. 2012 18:55:33 by Hibernate Tools 3.2.1.GA



/**
 * DetailssortieelementId generated by hbm2java
 */
public class DetailssortieelementId  implements java.io.Serializable {


     private String idsortie;
     private String idelement;

    public DetailssortieelementId() {
    }

    public DetailssortieelementId(String idsortie, String idelement) {
       this.idsortie = idsortie;
       this.idelement = idelement;
    }
   
    public String getIdsortie() {
        return this.idsortie;
    }
    
    public void setIdsortie(String idsortie) {
        this.idsortie = idsortie;
    }
    public String getIdelement() {
        return this.idelement;
    }
    
    public void setIdelement(String idelement) {
        this.idelement = idelement;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailssortieelementId) ) return false;
		 DetailssortieelementId castOther = ( DetailssortieelementId ) other; 
         
		 return ( (this.getIdsortie()==castOther.getIdsortie()) || ( this.getIdsortie()!=null && castOther.getIdsortie()!=null && this.getIdsortie().equals(castOther.getIdsortie()) ) )
 && ( (this.getIdelement()==castOther.getIdelement()) || ( this.getIdelement()!=null && castOther.getIdelement()!=null && this.getIdelement().equals(castOther.getIdelement()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdsortie() == null ? 0 : this.getIdsortie().hashCode() );
         result = 37 * result + ( getIdelement() == null ? 0 : this.getIdelement().hashCode() );
         return result;
   }   


}


