package com.lds.vo;
// Generated 13 juil. 2012 07:24:47 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Devis generated by hbm2java
 */
public class Devis  implements java.io.Serializable {


     private String numdevis;
     private Date datedevis;
     private String liendevis;
     private BigDecimal montantdevis;
     private String descdevis;
     private Set affaires = new HashSet(0);

    public Devis() {
    }

	
    public Devis(String numdevis) {
        this.numdevis = numdevis;
    }
    public Devis(String numdevis, Date datedevis, String liendevis, BigDecimal montantdevis, String descdevis, Set affaires) {
       this.numdevis = numdevis;
       this.datedevis = datedevis;
       this.liendevis = liendevis;
       this.montantdevis = montantdevis;
       this.descdevis = descdevis;
       this.affaires = affaires;
    }
   
    public String getNumdevis() {
        return this.numdevis;
    }
    
    public void setNumdevis(String numdevis) {
        this.numdevis = numdevis;
    }
    public Date getDatedevis() {
        return this.datedevis;
    }
    
    public void setDatedevis(Date datedevis) {
        this.datedevis = datedevis;
    }
    public String getLiendevis() {
        return this.liendevis;
    }
    
    public void setLiendevis(String liendevis) {
        this.liendevis = liendevis;
    }
    public BigDecimal getMontantdevis() {
        return this.montantdevis;
    }
    
    public void setMontantdevis(BigDecimal montantdevis) {
        this.montantdevis = montantdevis;
    }
    public String getDescdevis() {
        return this.descdevis;
    }
    
    public void setDescdevis(String descdevis) {
        this.descdevis = descdevis;
    }
    public Set getAffaires() {
        return this.affaires;
    }
    
    public void setAffaires(Set affaires) {
        this.affaires = affaires;
    }




}


