package com.lds.vo;
// Generated 25 aout 2012 10:08:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Devis generated by hbm2java
 */
public class Devis  implements java.io.Serializable {


     private String numdevis;
     private String idprojet;
     private Date datedevis;
     private String liendevis;
     private Double montantdevis;
     private String descdevis;

    public Devis() {
    }

	
    public Devis(String numdevis, String idprojet) {
        this.numdevis = numdevis;
        this.idprojet = idprojet;
    }
    public Devis(String numdevis, String idprojet, Date datedevis, String liendevis, Double montantdevis, String descdevis) {
       this.numdevis = numdevis;
       this.idprojet = idprojet;
       this.datedevis = datedevis;
       this.liendevis = liendevis;
       this.montantdevis = montantdevis;
       this.descdevis = descdevis;
    }
   
    public String getNumdevis() {
        return this.numdevis;
    }
    
    public void setNumdevis(String numdevis) {
        this.numdevis = numdevis;
    }
    public String getIdprojet() {
        return this.idprojet;
    }
    
    public void setIdprojet(String idprojet) {
        this.idprojet = idprojet;
    }
    public Date getDatedevis() {
        return this.datedevis;
    }
    
    public void setDatedevis(Date datedevis) {
        this.datedevis = datedevis;
    }
    public String getLiendevis() {
        return this.liendevis;
    }
    
    public void setLiendevis(String liendevis) {
        this.liendevis = liendevis;
    }
    public Double getMontantdevis() {
        return this.montantdevis;
    }
    
    public void setMontantdevis(Double montantdevis) {
        this.montantdevis = montantdevis;
    }
    public String getDescdevis() {
        return this.descdevis;
    }
    
    public void setDescdevis(String descdevis) {
        this.descdevis = descdevis;
    }




}


