package com.lds.vo;
// Generated 7 aout 2012 07:43:48 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Facture generated by hbm2java
 */
public class Facture  implements java.io.Serializable {


     private String numfacture;
     private Projet projet;
     private Date datefacture;
     private String descfacture;
     private BigDecimal montantfacture;
     private String lienfacture;

    public Facture() {
    }

	
    public Facture(String numfacture, Projet projet) {
        this.numfacture = numfacture;
        this.projet = projet;
    }
    public Facture(String numfacture, Projet projet, Date datefacture, String descfacture, BigDecimal montantfacture, String lienfacture) {
       this.numfacture = numfacture;
       this.projet = projet;
       this.datefacture = datefacture;
       this.descfacture = descfacture;
       this.montantfacture = montantfacture;
       this.lienfacture = lienfacture;
    }
   
    public String getNumfacture() {
        return this.numfacture;
    }
    
    public void setNumfacture(String numfacture) {
        this.numfacture = numfacture;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public Date getDatefacture() {
        return this.datefacture;
    }
    
    public void setDatefacture(Date datefacture) {
        this.datefacture = datefacture;
    }
    public String getDescfacture() {
        return this.descfacture;
    }
    
    public void setDescfacture(String descfacture) {
        this.descfacture = descfacture;
    }
    public BigDecimal getMontantfacture() {
        return this.montantfacture;
    }
    
    public void setMontantfacture(BigDecimal montantfacture) {
        this.montantfacture = montantfacture;
    }
    public String getLienfacture() {
        return this.lienfacture;
    }
    
    public void setLienfacture(String lienfacture) {
        this.lienfacture = lienfacture;
    }




}


