package com.lds.vo;
// Generated 13 juil. 2012 11:34:38 by Hibernate Tools 3.2.1.GA



/**
 * InterventionId generated by hbm2java
 */
public class InterventionId  implements java.io.Serializable {


     private String idprojet;
     private String idintervention;

    public InterventionId() {
    }

    public InterventionId(String idprojet, String idintervention) {
       this.idprojet = idprojet;
       this.idintervention = idintervention;
    }
   
    public String getIdprojet() {
        return this.idprojet;
    }
    
    public void setIdprojet(String idprojet) {
        this.idprojet = idprojet;
    }
    public String getIdintervention() {
        return this.idintervention;
    }
    
    public void setIdintervention(String idintervention) {
        this.idintervention = idintervention;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InterventionId) ) return false;
		 InterventionId castOther = ( InterventionId ) other; 
         
		 return ( (this.getIdprojet()==castOther.getIdprojet()) || ( this.getIdprojet()!=null && castOther.getIdprojet()!=null && this.getIdprojet().equals(castOther.getIdprojet()) ) )
 && ( (this.getIdintervention()==castOther.getIdintervention()) || ( this.getIdintervention()!=null && castOther.getIdintervention()!=null && this.getIdintervention().equals(castOther.getIdintervention()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdprojet() == null ? 0 : this.getIdprojet().hashCode() );
         result = 37 * result + ( getIdintervention() == null ? 0 : this.getIdintervention().hashCode() );
         return result;
   }   


}


