package com.lds.vo;
// Generated 13 juil. 2012 07:24:47 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personnel generated by hbm2java
 */
public class Personnel  implements java.io.Serializable {


     private String idpersonnel;
     private Typeuser typeuser;
     private String nom;
     private String prenom;
     private Date datenaissance;
     private String adresse;
     private String tel;
     private String email;
     private String desc;
     private String fonction;
     private Set bonsorties = new HashSet(0);
     private Set privileges = new HashSet(0);
     private Set detailstachepersonnels = new HashSet(0);
     private Set reservations = new HashSet(0);

    public Personnel() {
    }

	
    public Personnel(String idpersonnel, Typeuser typeuser) {
        this.idpersonnel = idpersonnel;
        this.typeuser = typeuser;
    }
    public Personnel(String idpersonnel, Typeuser typeuser, String nom, String prenom, Date datenaissance, String adresse, String tel, String email, String desc, String fonction, Set bonsorties, Set privileges, Set detailstachepersonnels, Set reservations) {
       this.idpersonnel = idpersonnel;
       this.typeuser = typeuser;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.adresse = adresse;
       this.tel = tel;
       this.email = email;
       this.desc = desc;
       this.fonction = fonction;
       this.bonsorties = bonsorties;
       this.privileges = privileges;
       this.detailstachepersonnels = detailstachepersonnels;
       this.reservations = reservations;
    }
   
    public String getIdpersonnel() {
        return this.idpersonnel;
    }
    
    public void setIdpersonnel(String idpersonnel) {
        this.idpersonnel = idpersonnel;
    }
    public Typeuser getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(Typeuser typeuser) {
        this.typeuser = typeuser;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public Set getBonsorties() {
        return this.bonsorties;
    }
    
    public void setBonsorties(Set bonsorties) {
        this.bonsorties = bonsorties;
    }
    public Set getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Set privileges) {
        this.privileges = privileges;
    }
    public Set getDetailstachepersonnels() {
        return this.detailstachepersonnels;
    }
    
    public void setDetailstachepersonnels(Set detailstachepersonnels) {
        this.detailstachepersonnels = detailstachepersonnels;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


