package com.lds.vo;
// Generated 13 juil. 2012 07:24:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private String idpriv;
     private String lienpriv;
     private Set personnels = new HashSet(0);

    public Privilege() {
    }

	
    public Privilege(String idpriv) {
        this.idpriv = idpriv;
    }
    public Privilege(String idpriv, String lienpriv, Set personnels) {
       this.idpriv = idpriv;
       this.lienpriv = lienpriv;
       this.personnels = personnels;
    }
   
    public String getIdpriv() {
        return this.idpriv;
    }
    
    public void setIdpriv(String idpriv) {
        this.idpriv = idpriv;
    }
    public String getLienpriv() {
        return this.lienpriv;
    }
    
    public void setLienpriv(String lienpriv) {
        this.lienpriv = lienpriv;
    }
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }




}


