package com.lds.vo;
// Generated 25 aout 2012 10:08:18 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projet generated by hbm2java
 */
public class Projet  implements java.io.Serializable {


     private String idprojet;
     private Client client;
     private Date datedebutaffaire;
     private Date datefinaffaire;
     private String descprojet;
     private BigDecimal montantaffaire;
     private Date dateintervention;
     private String lieuintervention;
     private String typeprojet;
     private Set factures = new HashSet(0);
     private Set bonsorties = new HashSet(0);
     private Set boncommandes = new HashSet(0);
     private Set taches = new HashSet(0);
     private Set besoins = new HashSet(0);

    public Projet() {
    }

	
    public Projet(String idprojet, Client client) {
        this.idprojet = idprojet;
        this.client = client;
    }
    public Projet(String idprojet, Client client, Date datedebutaffaire, Date datefinaffaire, String descprojet, BigDecimal montantaffaire, Date dateintervention, String lieuintervention, String typeprojet, Set factures, Set bonsorties, Set boncommandes, Set taches, Set besoins) {
       this.idprojet = idprojet;
       this.client = client;
       this.datedebutaffaire = datedebutaffaire;
       this.datefinaffaire = datefinaffaire;
       this.descprojet = descprojet;
       this.montantaffaire = montantaffaire;
       this.dateintervention = dateintervention;
       this.lieuintervention = lieuintervention;
       this.typeprojet = typeprojet;
       this.factures = factures;
       this.bonsorties = bonsorties;
       this.boncommandes = boncommandes;
       this.taches = taches;
       this.besoins = besoins;
    }
   
    public String getIdprojet() {
        return this.idprojet;
    }
    
    public void setIdprojet(String idprojet) {
        this.idprojet = idprojet;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDatedebutaffaire() {
        return this.datedebutaffaire;
    }
    
    public void setDatedebutaffaire(Date datedebutaffaire) {
        this.datedebutaffaire = datedebutaffaire;
    }
    public Date getDatefinaffaire() {
        return this.datefinaffaire;
    }
    
    public void setDatefinaffaire(Date datefinaffaire) {
        this.datefinaffaire = datefinaffaire;
    }
    public String getDescprojet() {
        return this.descprojet;
    }
    
    public void setDescprojet(String descprojet) {
        this.descprojet = descprojet;
    }
    public BigDecimal getMontantaffaire() {
        return this.montantaffaire;
    }
    
    public void setMontantaffaire(BigDecimal montantaffaire) {
        this.montantaffaire = montantaffaire;
    }
    public Date getDateintervention() {
        return this.dateintervention;
    }
    
    public void setDateintervention(Date dateintervention) {
        this.dateintervention = dateintervention;
    }
    public String getLieuintervention() {
        return this.lieuintervention;
    }
    
    public void setLieuintervention(String lieuintervention) {
        this.lieuintervention = lieuintervention;
    }
    public String getTypeprojet() {
        return this.typeprojet;
    }
    
    public void setTypeprojet(String typeprojet) {
        this.typeprojet = typeprojet;
    }
    public Set getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set factures) {
        this.factures = factures;
    }
    public Set getBonsorties() {
        return this.bonsorties;
    }
    
    public void setBonsorties(Set bonsorties) {
        this.bonsorties = bonsorties;
    }
    public Set getBoncommandes() {
        return this.boncommandes;
    }
    
    public void setBoncommandes(Set boncommandes) {
        this.boncommandes = boncommandes;
    }
    public Set getTaches() {
        return this.taches;
    }
    
    public void setTaches(Set taches) {
        this.taches = taches;
    }
    public Set getBesoins() {
        return this.besoins;
    }
    
    public void setBesoins(Set besoins) {
        this.besoins = besoins;
    }




}


