package com.lds.vo;
// Generated 16 juil. 2012 17:30:31 by Hibernate Tools 3.2.1.GA



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private String numreservation;
     private Element element;
     private Projet projet;
     private Personnel personnel;
     private Integer qntreserve;

    public Reservation() {
    }

	
    public Reservation(String numreservation, Personnel personnel) {
        this.numreservation = numreservation;
        this.personnel = personnel;
    }
    public Reservation(String numreservation, Element element, Projet projet, Personnel personnel, Integer qntreserve) {
       this.numreservation = numreservation;
       this.element = element;
       this.projet = projet;
       this.personnel = personnel;
       this.qntreserve = qntreserve;
    }
   
    public String getNumreservation() {
        return this.numreservation;
    }
    
    public void setNumreservation(String numreservation) {
        this.numreservation = numreservation;
    }
    public Element getElement() {
        return this.element;
    }
    
    public void setElement(Element element) {
        this.element = element;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public Personnel getPersonnel() {
        return this.personnel;
    }
    
    public void setPersonnel(Personnel personnel) {
        this.personnel = personnel;
    }
    public Integer getQntreserve() {
        return this.qntreserve;
    }
    
    public void setQntreserve(Integer qntreserve) {
        this.qntreserve = qntreserve;
    }




}


