package com.lds.vo;
// Generated 20 juil. 2012 18:55:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tache generated by hbm2java
 */
public class Tache  implements java.io.Serializable {


     private String numtache;
     private Affaire affaire;
     private String designationtache;
     private Integer durefabrication;
     private String lienimplemenation;
     private String lienschema;
     private String lieutache;
     private String typetache;
     private Set detailstachepersonnels = new HashSet(0);

    public Tache() {
    }

	
    public Tache(String numtache, Affaire affaire) {
        this.numtache = numtache;
        this.affaire = affaire;
    }
    public Tache(String numtache, Affaire affaire, String designationtache, Integer durefabrication, String lienimplemenation, String lienschema, String lieutache, String typetache, Set detailstachepersonnels) {
       this.numtache = numtache;
       this.affaire = affaire;
       this.designationtache = designationtache;
       this.durefabrication = durefabrication;
       this.lienimplemenation = lienimplemenation;
       this.lienschema = lienschema;
       this.lieutache = lieutache;
       this.typetache = typetache;
       this.detailstachepersonnels = detailstachepersonnels;
    }
   
    public String getNumtache() {
        return this.numtache;
    }
    
    public void setNumtache(String numtache) {
        this.numtache = numtache;
    }
    public Affaire getAffaire() {
        return this.affaire;
    }
    
    public void setAffaire(Affaire affaire) {
        this.affaire = affaire;
    }
    public String getDesignationtache() {
        return this.designationtache;
    }
    
    public void setDesignationtache(String designationtache) {
        this.designationtache = designationtache;
    }
    public Integer getDurefabrication() {
        return this.durefabrication;
    }
    
    public void setDurefabrication(Integer durefabrication) {
        this.durefabrication = durefabrication;
    }
    public String getLienimplemenation() {
        return this.lienimplemenation;
    }
    
    public void setLienimplemenation(String lienimplemenation) {
        this.lienimplemenation = lienimplemenation;
    }
    public String getLienschema() {
        return this.lienschema;
    }
    
    public void setLienschema(String lienschema) {
        this.lienschema = lienschema;
    }
    public String getLieutache() {
        return this.lieutache;
    }
    
    public void setLieutache(String lieutache) {
        this.lieutache = lieutache;
    }
    public String getTypetache() {
        return this.typetache;
    }
    
    public void setTypetache(String typetache) {
        this.typetache = typetache;
    }
    public Set getDetailstachepersonnels() {
        return this.detailstachepersonnels;
    }
    
    public void setDetailstachepersonnels(Set detailstachepersonnels) {
        this.detailstachepersonnels = detailstachepersonnels;
    }




}


