package com.lds.vo;
// Generated 20 juil. 2012 11:53:18 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Typeuser generated by hbm2java
 */
public class Typeuser  implements java.io.Serializable {


     private int typeuser;
     private String nompriv;
     private Set personnels = new HashSet(0);

    public Typeuser() {
    }

	
    public Typeuser(int typeuser) {
        this.typeuser = typeuser;
    }
    public Typeuser(int typeuser, String nompriv, Set personnels) {
       this.typeuser = typeuser;
       this.nompriv = nompriv;
       this.personnels = personnels;
    }
   
    public int getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(int typeuser) {
        this.typeuser = typeuser;
    }
    public String getNompriv() {
        return this.nompriv;
    }
    
    public void setNompriv(String nompriv) {
        this.nompriv = nompriv;
    }
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }




}


