package com.lds.vo;
// Generated 13 juil. 2012 07:24:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Typeuser generated by hbm2java
 */
public class Typeuser  implements java.io.Serializable {


     private int typeuser;
     private String nom_type;
     private Set personnels = new HashSet(0);

    public Typeuser() {
    }

	
    public Typeuser(int typeuser) {
        this.typeuser = typeuser;
    }
    public Typeuser(int typeuser, Set personnels) {
       this.typeuser = typeuser;
       this.personnels = personnels;
    }
   
    public int getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(int typeuser) {
        this.typeuser = typeuser;
    }

    public String getNom_type() {
        return nom_type;
    }

    public void setNom_type(String nom_type) {
        this.nom_type = nom_type;
    }
    
    
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }




}


